name: Mark Stale Issues and PRs
on:
  schedule:
    - cron: '0 8 * * *' # Roda todo dia às 8h UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Esta issue está inativa há 60 dias. Será fechada se não houver mais atividade.'
          stale-pr-message: 'Este PR está inativo há 60 dias. Será fechado se não houver mais atividade.'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'