name: Sync Labels

on:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yml"
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync GitHub Labels
        uses: EndBug/label-sync@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          config-file: ".github/labels.yml"
          delete-other-labels: true